version: '3'
services:
  node:
    build:
      context: .
    command: npm run dev
    ports:
      - 80:3000
    volumes:
      - ./:/app
    environment:
      - DBHOST=mongo
      - DBPORT=27017
      - DATA=gateways-dev
      - WAIT=5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
#    volumes:
#      - mongodb:/data/db
