version: '3'
services:
  node:
    build:
      context: .
    command: npm run start
    ports:
      - 80:3000
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
#    volumes:
#      - mongodb:/data/db
