version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 80:3000
    volumes:
      - ./:/app
    environment:
      - DBHOST=mongo
      - DBPORT=27017
      - DATA=gateways
      - WAIT=5000
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
#    volumes:
#      - mongodb:/data/db
