version: '3'
services:
  node:
    build:
      context: .
      args: [ "NODESCRIPT=test" ]
    ports:
      - 80:3000
    environment:
      - DBHOST:mongo
      - DBPORT:27017
      - DATA:gateways-test
      - WAIT:5000
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
#    volumes:
#      - mongodb:/data/db
